.ds q \N'34'
.TH TSLIB __drivermansuffix__ __vendorversion__
.SH NAME
tslib \- tslib input driver
.SH SYNOPSIS
.nf
.B "Section \*qInputDevice\*q"
.BI "  Identifier \*q" tslib \*q
.B  "  Driver \*qtslib\*q"
.BI "  Option \*qDevice\*q   \*q" /dev/event0 \*q
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B tslib
is an tslib Xorg input driver. It supports touchscreen devices accessed by
libts and aims to make them easy to use for X.org systems.

Please refer to xorg.conf(5) for general configuration
details and for options that can be used with all input drivers and to
ts.conf(5) for tslib modules configuration.
.PP
.SH "SEE ALSO"
Xorg(1), xorg.conf(5), xorgconfig(1), Xserver(1), X(7), ts.conf(5).
.SH AUTHORS
Martin Kepplinger <martink@posteo.de>
.fi
Sascha Hauer <s.hauer@pengutronix.de>
.fi
Clement Chauplannaz, Thales e-Transactions <chauplac@gmail.com>
.fi
Michael Olbrich <m.olbrich@pengutronix.de>
